### PR TITLE
nom-based parser

### PR DESCRIPTION
**Pull request by JamesFysh**
Not sure how I'm 12 commits ahead of upstream.

I've introduced some unit-tests for the existing parser.  One of these panics.  Wrote an equivalent parser in nom which passes all these tests.

### CODE REVIEW

**Comment by dcarosone** [comment]
I called out a spurious suggestion to use nom for these messages in the talk session. I love nom, 

But looking at the structs I think it will (almost by accident) basically wind up working fine with serde and bincode and/or ssmarshal, and they're more or less semantically equivalent to the repr(C, packed) cast anyway. 

So I didn't bother doing this. I'm glad someone did!

**Comment by JamesFysh** [comment]
The original function has a lot of busy-work code to do book-keeping, and it still gets it wrong in at least one instance (partially-complete packets cause a panic).  Not sure if serde + bincode/ssmarshal improves on that aspect, but if you still have to do onerous book-keeping then I can see the value in nom :smile:

Definitely scratched an itch - Nom seemed like fun, but I never had a real use-case.  However, it also demonstrated the downside of nom - macro's "all the way down" means nasty errors when things go wrong.  If I do it again, I will be building the parser up piece-by-piece, rather than a monolithic parser all in one hit.  Having said that, I spent a lot more time fighting the borrow-checker than compile-errors in nom!

**Comment by JamesFysh** [comment]
Noticed I missed the "mode == 0x0b" check.  More unit-tests, found another (semi) bug in the original parse method (it doesn't consume bytes off the chunk vector if non-0x0b-mode packets are encountered).

**Comment by JamesFysh** [comment]
Restarting my fork of this repo so I can correctly apply changes on top of develop branch

**Pull request closed without merging**
